conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from conf.utils import likes_enable
from digest.urls import urlpatterns as digest_url
from frontend.urls import urlpatterns as frontend_url

admin.autodiscover()


urlpatterns = [
    path("", include((frontend_url, "frontend"), namespace="frontend")),
    path("", include((digest_url, "digest"), namespace="digest")),
    path("admin/", admin.site.urls),
    path("taggit_autosuggest/", include("taggit_autosuggest.urls")),
    # path('account/', include('account.urls')),
    re_path(r"^\.well-known/", include("letsencrypt.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "landings" in settings.INSTALLED_APPS:
    from landings.urls import urlpatterns as landings_url

    urlpatterns.append(path("", include((landings_url, "landings"), namespace="landings")))

if "jobs" in settings.INSTALLED_APPS:
    from jobs.urls import urlpatterns as jobs_url

    urlpatterns.append(path("", include((jobs_url, "jobs"), namespace="jobs")))

if likes_enable():
    from likes.urls import urlpatterns as like_urls

    urlpatterns.append(path("likes/", include(like_urls)))

if settings.DEBUG:
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

if "debug_toolbar" in settings.INSTALLED_APPS and settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

digest/urls.py
from django.urls import path

from .views import AddNews, IssuesList, IssueView, ItemView, NewsList, get_items_json

app_name = "digest"
urlpatterns = [
    path("view/<int:pk>/", ItemView.as_view(), name="item"),
    path("issues/", IssuesList.as_view(), name="issues"),
    path("issue/<int:pk>/", IssueView.as_view(), name="issue_view"),
    path("add/", AddNews.as_view(), name="addnews"),
    path("feed/", NewsList.as_view(), name="feed"),
    path("api/items/<int:year>/<int:month>/<int:day>/", get_items_json),
]

frontend/urls.py
from django.conf import settings
from django.http import HttpResponse
from django.urls import path

from frontend.views import FriendsView, IndexView, Sitemap

from .feeds import (
    AllEntriesFeed,
    IssuesFeed,
    ItemArticleFeed,
    ItemAuthorsFeed,
    ItemBookDocFeed,
    ItemEventFeed,
    ItemNewsFeed,
    ItemPackagesFeed,
    ItemRecommendFeed,
    ItemReleaseFeed,
    ItemVideoFeed,
    RawEntriesFeed,
    RussianEntriesFeed,
    TurboFeed,
    TwitterEntriesFeed,
)

feed = TurboFeed()
feed.configure_analytics_yandex(settings.YANDEX_METRIKA_ID)


def indexnow_key(request):
    return HttpResponse(settings.SEO_INDEXNOW_KEY)


app_name = "frontend"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    # SEO
    path(f"{settings.SEO_INDEXNOW_KEY}.txt", indexnow_key, name="indexnow-key"),
    # RSS
    path("rss/", AllEntriesFeed(), name="rss"),
    path("rss/raw", RawEntriesFeed(), name="rss_raw"),
    path("rss/direct/", AllEntriesFeed(), name="rss_direct"),
    path("rss/twitter/", TwitterEntriesFeed(), name="rss_twitter"),
    path("rss/ru/", RussianEntriesFeed(), name="russian_rss"),
    path("rss/issues/", IssuesFeed(), name="issues_rss"),  # hindi
    # solution
    path("rss/video/", ItemVideoFeed(), name="video_rss"),
    path("rss/recommend/", ItemRecommendFeed(), name="recommend_rss"),
    path("rss/news/", ItemNewsFeed(), name="news_rss"),
    path("rss/bookdoc/", ItemBookDocFeed(), name="book_doc_rss"),
    path("rss/event/", ItemEventFeed(), name="event_rss"),
    path("rss/article/", ItemArticleFeed(), name="article_rss"),
    path("rss/authors/", ItemAuthorsFeed(), name="authors_rss"),
    path("rss/release/", ItemReleaseFeed(), name="release_rss"),
    path("rss/packages/", ItemPackagesFeed(), name="packages_rss"),
    path("turbo/", feed),
    path("sitemap.xml", Sitemap.as_view(), name="sitemap"),
    path("friends/", FriendsView.as_view(), name="friends"),
]

templates/blocks/_adv.html
{% load static %}
{% load i18n %}

<div class="card card-block">
    <h4 class="card-title">{% trans 'Place your ads' %}</h4>
    <p class="card-text">{% trans 'Write:' %} <a href="mailto:mail@pythondigest.ru">mail@pythondigest.ru</a></p>
</div>

templates/blocks/_adv_yandex.html
<!-- Yandex.RTB R-A-287000-1 -->
<div id="yandex_rtb_R-A-287000-1"></div>
<script type="text/javascript">
    (function(w, d, n, s, t) {
        w[n] = w[n] || [];
        w[n].push(function() {
            Ya.Context.AdvManager.render({
                blockId: "R-A-287000-1",
                renderTo: "yandex_rtb_R-A-287000-1",
                async: true
            });
        });
        t = d.getElementsByTagName("script")[0];
        s = d.createElement("script");
        s.type = "text/javascript";
        s.src = "//an.yandex.ru/system/context.js";
        s.async = true;
        t.parentNode.insertBefore(s, t);
    })(this, this.document, "yandexContextAsyncCallbacks");
</script>

templates/blocks/_footer.html
<div class="container-fluid">
    <div class="footer navbar-fixed-bottom">
        <div class="footer-contact col-md-4">
            Контакты:
            <a href="https://github.com/pythondigest/pythondigest"
               title="GitHub"><i
                    class="fa-brands fa-github fa-lg"></i></a>
              <a href="https://t.me/axsapronov"
               title="Telegram"><i
                    class="fa-brands fa-telegram fa-lg"></i></a>

            <a href="mailto:mail@pythondigest.ru" title="mail@pythondigest.ru" aria-label="Email"><i
              class="fa fa-envelope fa-lg"></i></a>
            &nbsp;&nbsp;
            Фиды:
            <a href="{% url 'frontend:rss' %}" title="RSS feed"><i
                    class="fa fa-rss-square fa-lg"></i></a>
            &nbsp;<a href="https://twitter.com/pydigest" title="Twitter feed"><i
                class="fa-brands fa-twitter-square fa-lg"></i></a>

        </div>
        <div class="col-md-4 footer-contact" align="center">
            <a href="https://incidenta.tech/?utm_source=pydigest">Наш тренажер IT-инцидентов для DevOps/SRE</a>
        </div>
        <div class="footer-copyright col-md-4" align="right">
            &copy; Дайджест новостей о python 2013 — {% now "Y" %}
        </div>
    </div>
</div>

templates/blocks/_friends.html
{% load static %}

templates/blocks/_item.html
{% load micawber_tags %}
{% load common %}

<noindex>
    <div class="issue-item">
    <span title="Язык новости" class="badge issue-item-language issue-item-bages issue-item-resource
    {% if item.language == 'en' %}
        en
    {% elif item.language == 'ru' %}
        ru
    {% endif %}
    ">
    &nbsp;
    </span>
        <a class="issue-item-title"
           onclick="trackUrl({{ item.pk }}, '{{ item.section }}', '{{ item.get_tags_str }}');"
           rel="nofollow"
           href="{{ item.link }}"
           target="_blank">
            {{ item.title }}
        </a>
    <span class="issue-item-bages">
        {% if item.resource %}
            <a title="Источник новости"
               rel="nofollow"
               href="{{ item.resource.link }}"
               class="badge issue-item-resource"
               target="_blank">
                {{ item.resource }}
            </a>
        {% endif %}

        {% if item.is_editors_choice %}
            <span class="badge issue-item-resource">
              <i title="Выбор редакции"
                 class="goodnews fa fa-thumbs-o-up"></i>
            </span>
        {% endif %}
    </span>
        <p class="text-muted issue-item-description">
{#            <pre class="python">#}
            {{ item.description|default:''|highlight_code|safe}}
{#            </pre>#}

        </p>

        {% if item.additionally and item.additionally|oembed_no_urlize != item.additionally %}
            {{ item.additionally|oembed}}
        {% endif %}
        {% if  item.link|oembed_no_urlize != item.link  %}
            {{ item.link|oembed}}
        {% endif %}


    </div>
</noindex>

templates/blocks/_jumb.html
{% load i18n %}
{% load account_tags %}
{% load static %}
{% load common %}


<div class="jumb container-fluid">



    <div class="row">
        <div class="container text-center">
            <div class="jumb-text col-md-12">
              <h3>IT-новости про Python, которые стоит знать</h3>
                <p><big>Собрали в одном месте самые важные ссылки<br>{% autoescape off %}{% jumb_ads %}{% endautoescape %}</big></p>
            </div>
{% comment %}
            <div class="col-md-3">
                <a class="btn btn-lg btn-success add-button"
                   href="{% url 'digest:addnews' %}">Добавить новость</a>
            </div> {% endcomment %}

        </div>
    </div>
</div>

templates/blocks/_menu.html
{% load i18n %}
{% load account_tags %}
{% load static %}


<nav class="navbar navbar-default navbar-digest" role="navigation">

    <a class="navbar-brand" href="{% url 'frontend:index' %}">
        <span><img src="{% static "img/logo.png" %}" width="30px" height="30px" alt="logo"></span><big>&nbsp;Python Дайджест</big>
    </a>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"  aria-label="Menu"
                data-target=".navbar-collapse" id="menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            {% comment %} <li><a href="{% url 'digest:feed' %}">НОВОСТИ</a></li> {% endcomment %}
            <li><a href="{% url 'digest:issues' %}">ВЫПУСКИ</a></li>
            {% comment %} <li><a href="{% url 'frontend:friends' %}">НАШИ ДРУЗЬЯ</a></li> {% endcomment %}
            {% comment %}<li><a href="https://boosty.to/pydigest">ПОМОЧЬ ПРОЕКТУ</a></li>{% endcomment %}
            <li><a href="{% url 'digest:addnews' %}">ДОБАВИТЬ НОВОСТЬ</a></li>
        </ul>
    </div>
</nav>

templates/blocks/_messages.html
{% load common %}
{% for message in messages %}
    <div class="alert fade in {% get_message_tags message %}">
        <button type="button" class="close"
                data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}

templates/blocks/_money.html
{% load common %}

<div class="panel panel-default">
    <div class="panel-heading">
        <center><h4>{% money_block_title %}</h4></center>
    </div>
    <div class="panel-body">
        <center>
            <iframe frameborder="0" allowtransparency="true" scrolling="no"
                    src="https://money.yandex.ru/embed/donate.xml?account=41001222156458&quickpay=donate&payment-type-choice=on&default-sum=100&targets=%D0%9D%D0%B0+%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5+Python&target-visibility=on&project-name=Python+%D0%94%D0%B0%D0%B9%D0%B4%D0%B6%D0%B5%D1%81%D1%82&project-site=http%3A%2F%2Fpythondigest.ru%2F&button-text=02&successURL=http%3A%2F%2Fpythondigest.ru%2F"
                    width="490" height="131"></iframe>
        </center>
    </div>
</div>

templates/blocks/_orphus.html
<div class="panel panel-default widget">
    <div class="panel-body">
        <div class="text-center">
            <h3>Нашли опечатку? </h3><h4>Выделите фрагмент и отправьте нажатием
            Ctrl+Enter.</h4>

            <a href="http://orphus.ru" id="orphus" target="_blank"><img
                    alt="Система Orphus"/></a>

        </div>
    </div>
</div>

templates/blocks/_pagination.html
{% load common %}
{% if is_paginated %}
    <div class="container" align="center">
        <ul class="pagination pagination-sm">
            {% if page_obj.has_previous %}
                <li>
                    <a href="{% modify_url 'set_query_param' 'page' page_obj.previous_page_number %}">&larr;</a>
                    {% else %}
                <li class="disabled"><a>&larr;</a>
            {% endif %}

            {% for num in page_obj.page_range %}
                <li {% if num == page_obj.number %}class="active"{% endif %}>
                {% if not num %}
                    <li class="disabled"><a>...</a>
                {% else %}
                    {% if num == page_obj.number %}
                        <a>{{ num }}</a>
                    {% else %}
                        <a href="{% modify_url 'set_query_param' 'page' num %}">{{ num }}</a>
                    {% endif %}
                {% endif %}
            </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li>
                    <a href="{% modify_url 'set_query_param' 'page' page_obj.next_page_number %}">&rarr;</a>
                    {% else %}
                <li class="disabled"><a>&rarr;</a>
            {% endif %}
        </ul>

    </div>
{% endif %}

templates/blocks/_right_panel.html
<div class="panel panel-default panel-search">
    <div class="panel-body">
        <form action="{% url 'digest:feed' %}" role="form">
            <input type="text" name="q" type="text" class="search-input"
                   value="{{ request.GET.q|default:'' }}"
                   placeholder=" Поиск...">
        </form>

    </div>
</div>


{% comment %}


{% endcomment %}


{% comment %} {% include "blocks/_adv_yandex.html" %} {% endcomment %}
{% include 'advertising/blocks/ads.html' with ads=ads type='right' %}
{% with items=feed_items %}
    {% include "digest/blocks/_feed.html" %}
{% endwith %}

<ins class="mrg-tag" style="display:inline-block;text-decoration: none;" data-ad-client="ad-1177849" data-ad-slot="1177849"></ins>
<script>(MRGtag = window.MRGtag || []).push({})</script>

{% include "blocks/_friends.html" %}
{% with items=favorite_items %}
    {% include "digest/blocks/_favorite_items.html" %}
{% endwith %}

{% comment %} {% include "blocks/_adv.html" %} {% endcomment %}
{% comment %} {% include "blocks/_orphus.html" %} {% endcomment %}