conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from conf.utils import likes_enable
from digest.urls import urlpatterns as digest_url
from frontend.urls import urlpatterns as frontend_url

admin.autodiscover()


urlpatterns = [
    path("", include((frontend_url, "frontend"), namespace="frontend")),
    path("", include((digest_url, "digest"), namespace="digest")),
    path("admin/", admin.site.urls),
    path("taggit_autosuggest/", include("taggit_autosuggest.urls")),
    # path('account/', include('account.urls')),
    re_path(r"^\.well-known/", include("letsencrypt.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "landings" in settings.INSTALLED_APPS:
    from landings.urls import urlpatterns as landings_url

    urlpatterns.append(path("", include((landings_url, "landings"), namespace="landings")))

if "jobs" in settings.INSTALLED_APPS:
    from jobs.urls import urlpatterns as jobs_url

    urlpatterns.append(path("", include((jobs_url, "jobs"), namespace="jobs")))

if likes_enable():
    from likes.urls import urlpatterns as like_urls

    urlpatterns.append(path("likes/", include(like_urls)))

if settings.DEBUG:
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

if "debug_toolbar" in settings.INSTALLED_APPS and settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

digest/urls.py
from django.urls import path

from .views import AddNews, IssuesList, IssueView, ItemView, NewsList, get_items_json

app_name = "digest"
urlpatterns = [
    path("view/<int:pk>/", ItemView.as_view(), name="item"),
    path("issues/", IssuesList.as_view(), name="issues"),
    path("issue/<int:pk>/", IssueView.as_view(), name="issue_view"),
    path("add/", AddNews.as_view(), name="addnews"),
    path("feed/", NewsList.as_view(), name="feed"),
    path("api/items/<int:year>/<int:month>/<int:day>/", get_items_json),
]

frontend/urls.py
from django.conf import settings
from django.http import HttpResponse
from django.urls import path

from frontend.views import FriendsView, IndexView, Sitemap

from .feeds import (
    AllEntriesFeed,
    IssuesFeed,
    ItemArticleFeed,
    ItemAuthorsFeed,
    ItemBookDocFeed,
    ItemEventFeed,
    ItemNewsFeed,
    ItemPackagesFeed,
    ItemRecommendFeed,
    ItemReleaseFeed,
    ItemVideoFeed,
    RawEntriesFeed,
    RussianEntriesFeed,
    TurboFeed,
    TwitterEntriesFeed,
)

feed = TurboFeed()
feed.configure_analytics_yandex(settings.YANDEX_METRIKA_ID)


def indexnow_key(request):
    return HttpResponse(settings.SEO_INDEXNOW_KEY)


app_name = "frontend"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    # SEO
    path(f"{settings.SEO_INDEXNOW_KEY}.txt", indexnow_key, name="indexnow-key"),
    # RSS
    path("rss/", AllEntriesFeed(), name="rss"),
    path("rss/raw", RawEntriesFeed(), name="rss_raw"),
    path("rss/direct/", AllEntriesFeed(), name="rss_direct"),
    path("rss/twitter/", TwitterEntriesFeed(), name="rss_twitter"),
    path("rss/ru/", RussianEntriesFeed(), name="russian_rss"),
    path("rss/issues/", IssuesFeed(), name="issues_rss"),  # hindi
    # solution
    path("rss/video/", ItemVideoFeed(), name="video_rss"),
    path("rss/recommend/", ItemRecommendFeed(), name="recommend_rss"),
    path("rss/news/", ItemNewsFeed(), name="news_rss"),
    path("rss/bookdoc/", ItemBookDocFeed(), name="book_doc_rss"),
    path("rss/event/", ItemEventFeed(), name="event_rss"),
    path("rss/article/", ItemArticleFeed(), name="article_rss"),
    path("rss/authors/", ItemAuthorsFeed(), name="authors_rss"),
    path("rss/release/", ItemReleaseFeed(), name="release_rss"),
    path("rss/packages/", ItemPackagesFeed(), name="packages_rss"),
    path("turbo/", feed),
    path("sitemap.xml", Sitemap.as_view(), name="sitemap"),
    path("friends/", FriendsView.as_view(), name="friends"),
]

digest/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib import admin
from django.contrib.admin import widgets
from django.contrib.admin.options import get_ul_class
from django.forms import ChoiceField, ModelForm

from digest.models import Item

ITEM_STATUS_DEFAULT = "queue"
ITEM_STATUS_CHOICES = (
    ("queue", "В очередь"),
    ("moderated", "Отмодерировано"),
)


class ItemStatusForm(ModelForm):
    status = ChoiceField(
        label="Статус",
        widget=widgets.AdminRadioSelect(attrs={"class": get_ul_class(admin.HORIZONTAL)}),
        choices=ITEM_STATUS_CHOICES,
    )

    class Meta:
        model = Item
        fields = "__all__"
        widgets = {
            "description": CKEditorWidget,
        }


EMPTY_VALUES = (None, "")


class HoneypotWidget(forms.TextInput):
    is_hidden = True

    def __init__(self, attrs=None, html_comment=False, *args, **kwargs):
        self.html_comment = html_comment

        super().__init__(attrs, *args, **kwargs)

        if "class" not in self.attrs:
            self.attrs["style"] = "display:none"

    def render(self, *args, **kwargs):
        html = super().render(*args, **kwargs)

        if self.html_comment:
            html = "<!-- %s -->" % html

        return html


class HoneypotField(forms.Field):
    widget = HoneypotWidget

    def clean(self, value):
        if self.initial in EMPTY_VALUES and value in EMPTY_VALUES or value == self.initial:
            return value

        raise forms.ValidationError("Anti-spam field changed in value.")


class AddNewsForm(forms.ModelForm):
    name = HoneypotField()

    class Meta:
        model = Item
        fields = (
            "link",
            "section",
            "title",
            "language",
            "description",
        )

    def __init__(self, *args, **kwargs):
        kwargs["initial"] = {"section": 6}  # На форме 6й section будет помечен как selected
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs = {
            "class": "form-control small",
        }
        self.fields["title"].required = False
        self.fields["link"].widget.attrs = {
            "class": "form-control small",
        }
        self.fields["language"].widget.attrs = {
            "class": "form-control",
        }
        self.fields["description"].widget.attrs = {
            "class": "form-control",
        }
        self.fields["section"].widget.attrs = {
            "class": "form-control",
        }

digest/views.py
import datetime

from digg_paginator import DiggPaginator
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView

from advertising.mixins import AdsMixin

from .forms import AddNewsForm
from .mixins import CacheMixin, FavoriteItemsMixin, FeedItemsMixin
from .models import Issue, Item


class IssuesList(CacheMixin, ListView):
    """Список выпусков."""

    template_name = "digest/pages/issues_list.html"
    queryset = Issue.objects.filter(status="active").order_by("-published_at")
    context_object_name = "items"
    paginate_by = 12
    paginator_class = DiggPaginator
    cache_timeout = 300

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_menu_item"] = "issues_list"
        return context


class IssueView(CacheMixin, FavoriteItemsMixin, FeedItemsMixin, AdsMixin, DetailView):
    """Просмотр выпуска."""

    template_name = "digest/pages/issue.html"
    model = Issue
    cache_timeout = 300

    def get_queryset(self):
        return super().get_queryset().only("pk", "title", "description", "trend", "image")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = (
            self.object.item_set.filter(status="active")
            .exclude(section=None)
            .only(
                "title",
                "description",
                "tags",
                "section",
                "link",
                "language",
                "priority",
                "issue",
                "additionally",
            )
            .select_related("section")
            .prefetch_related("tags")
            .order_by("-section__priority", "-priority")
        )

        context.update(
            {
                "items": items,
                "active_menu_item": "issue_view",
            }
        )
        return context


class ItemView(FavoriteItemsMixin, CacheMixin, DetailView):
    """Просмотр отдельной новости."""

    template_name = "digest/pages/news_item.html"
    context_object_name = "item"
    model = Item
    cache_timeout = 300


class ItemsByTagView(AdsMixin, FavoriteItemsMixin, CacheMixin, ListView):
    """Лента новостей."""

    template_name = "news_by_tag.html"
    context_object_name = "items"
    paginate_by = 20
    paginator_class = DiggPaginator
    model = Item
    cache_timeout = 300

    def get_queryset(self):
        items = super().get_queryset().filter(status="active", activated_at__lte=datetime.datetime.now())
        tag = self.request.GET.get("tag")
        if tag in ["ru", "en"]:
            items = items.filter(tags__name__in=tag)

        items = items.prefetch_related("issue", "section")
        items = items.order_by("-activated_at", "-related_to_date")
        return items


class NewsList(FavoriteItemsMixin, CacheMixin, ListView):
    """Лента новостей."""

    template_name = "digest/pages/news_list.html"
    context_object_name = "items"
    paginate_by = 20
    paginator_class = DiggPaginator
    model = Item
    cache_timeout = 300

    def get_queryset(self):
        items = super().get_queryset().filter(status="active", activated_at__lte=datetime.datetime.now())
        lang = self.request.GET.get("lang")
        if lang in ["ru", "en"]:
            items = items.filter(language=lang)

        search = self.request.GET.get("q")
        if search:
            filters = Q(title__icontains=search) | Q(description__icontains=search)
            items = items.filter(filters)

        tag = self.request.GET.get("tag")
        if tag:
            items = items.filter(tags__name__in=[tag])

        section = self.request.GET.get("section", "")
        if section.isdigit():
            items = items.filter(section__pk=section)

        items = items.prefetch_related("issue", "section")
        items = items.order_by("-activated_at", "-related_to_date")
        return items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_menu_item"] = "feed"
        return context


class AddNews(FormView):
    template_name = "digest/pages/add_news.html"
    form_class = AddNewsForm

    def get_success_url(self):
        title = self.request.POST["title"].strip() or "Без заголовка"
        link = self.request.POST["link"]
        description = self.request.POST["description"]
        section = self.request.POST["section"]
        Item.objects.create(
            title=title,
            link=link,
            description=description,
            status="pending",
            related_to_date=datetime.datetime.now(),
            section_id=section,
        )
        messages.info(self.request, "Ваша ссылка успешно добавлена на рассмотрение")
        return reverse("frontend:index")


def get_items_json(request, year, month, day):
    result = {}
    items = Item.objects.filter(
        status="active",
        is_editors_choice=True,
        related_to_date__year=int(year),
        related_to_date__month=int(month),
        related_to_date__day=int(day),
    )
    result["ok"] = bool(items)
    if items:
        keys = [
            "title",
            "description",
            "section__title",
            "link",
            "language",
        ]
        result["items"] = list(items.values(*keys))
    return JsonResponse(result)

templates/digest/pages/add_news.html
{% extends "base.html" %}
{% block jumb %}
{% endblock %}
{% block content %}
{% load i18n %}

<div class="col-lg-8 col-lg-offset-2">
    <div class="card card-block">
        <h4 class="card-title">{% trans 'Add news to the Digest' %}</h4>
        <div class="alert alert-warning" role="alert">
            {% blocktrans %}We don't host news openly advertising.<br />
            Links to resources hosted on a paid for money, email us on: {% endblocktrans %}<a class="alert-link" href="mailto:mail@pythondigest.ru">mail@pythondigest.ru</a><br>
        </div>

        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}

        <form role="form" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}has-danger text-danger{% endif %}"
                     {% if field.is_hidden %}style="display: none" {% endif %}>
                    <label class="control-label" for="id_{{field.name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
                    {{ field }}
                    {% if field.errors %}
                        <span class="text-danger">{{ field.errors|striptags }}</span>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" value="{% trans 'Send' %}" class="btn btn-primary">{% trans 'Send' %}</button>
        </form>
    </div>
</div>

{% endblock %}

templates/digest/pages/issue.html
{% extends "base.html" %}
{% load thumbnail %}
{% load common %}
{% load micawber_tags %}
{% load i18n %}

{% load remdow %}
{% load video %}

{% block page_title %}{{ object.title }}{% if object.trend %} - {{ object.trend }}{% endif %} - {{ block.super }}{% endblock %}
{% block page_description %}{{ object.title }} - {{ block.super }}{% endblock %}

{% block extra_head %}
    {% thumbnail object.image "350" as im %}
        <link rel="image_src" href="http://pythondigest.ru{{ im.url }}">

        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="twitter:site" content="@pydigest"/>
        <meta name="twitter:title" content="{{ object.title }}"/>
        <meta name="twitter:description"
              content="{% trans 'The new release of weekly digest of news about #python is already in the air!' %}"/>
        <meta name="twitter:image" content="http://pythondigest.ru{{ im.url }}"/>
        <meta name="twitter:url" content="http://pythondigest.ru{{ object.link }}"/>
    {% endthumbnail %}

    <meta name="description" content='{{ object.description|striptags|truncatechars:500 }}'>
    <meta name="og:description" content='{{ object.description|striptags|truncatechars:500 }}'>
{% endblock %}

{% block body %}
{% if issue %}
    <div class="issue">
        {% include 'digest/blocks/_issue_anounce.html' %}

        {% regroup items by section as groups %}
        {% for data in groups %}
            <div class="items-group-container">

                {% with "before_section_"|add:data.grouper.title|unidecode|slugify as ads_section %}
                    <a type='button' data-toggle="collapse" data-target="#{{ ads_section }}">
                        <h2>{{ data.grouper.title }}</h2>
                    </a>
                    {% include 'advertising/blocks/ads.html' with ads=ads type=ads_section %}

                    <div id="{{ ads_section }}" class="collapse in">
                        {% for item in data.list %}
                            <div class="item-container">
                                <noindex>
                                    <div class="issue-item">
                                        {% include 'digest/blocks/_feed_item.html' with object=item language=True link_class='issue-item-title' comment=True like_link=True %}

                                        {% comment %}
                                        {% if item.additionally or item.section == 'Видео' %}
                                        {% include 'digest/blocks/_item_video.html' with link=item.additionally %}
                                        {% else %}
                                        {% include 'digest/blocks/_item_video.html' with link=item.link %}
                                        {% endif %}
                                        {% endcomment %}

                                    </div>
                                </noindex>
                            </div>
                        {% endfor %}
                    </div>
                {% endwith %}
            </div>
        {% endfor %}

        {% include 'advertising/blocks/ads.html' with ads=ads type='after_issue' %}

    </div>
    <div class="card card-block">
        {% with issue.pk|lower as id %}
            {% include "blocks/_disqus.html" with identifier='issue_'|add:id %}
        {% endwith %}
    </div>

{% endif %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% include 'blocks/_disqus_script.html' %}
{% endblock %}

templates/digest/pages/issues_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}

{% block fullwidth %}
        {% for item in object_list %}
            {% thumbnail item.image "x200" as im %}
            <div class="issue-card col-xs-12 col-md-4 col-lg-3 ">
                <a href="{% url 'digest:issue_view' pk=item.pk %}" title="{% blocktrans with title=item.title description=item.description|striptags %}Python digest, {{ title }}  {{ description }}{% endblocktrans %}">
                    <div class="card text-xs-center">
                        <div class="card-header">
                            <h4 class="card-title">{{ item.title }}</h4>
                            <p class="card-text">
                                <span class="text-muted">
                                ({{ item.date_from|date:"d.m.Y" }} - {{ item.date_to|date:"d.m.Y" }})
                                </span>
                            </p>
                        </div>
                        <div class="card-block">
                            <img src="{{ im.url }}" data-src="..." alt="{% blocktrans with title=item.title %}Python digest, {{ title }}{% endblocktrans %}">
                        </div>
                    </div>
                </a>
            </div>
            {% endthumbnail %}
        {% empty %}
            <p>{% trans 'No releases so far' %}</p>
        {% endfor %}
    {% include "blocks/_pagination.html" %}
{% endblock %}

{% block right_panel %}
{# hide right panel#}
{% endblock %}

{% block rss_url %}{% url 'frontend:issues_rss' %}{% endblock %}

templates/digest/pages/news_item.html
{% extends "base.html" %}
{% load micawber_tags %}
{% load pytils_dt %}
{% load common %}
{% load static %}
{% load i18n %}

{% block page_title %}{{ object.title }}{% endblock %}
{% block page_description %}
    {{ object.description|default:''|striptags|truncatechars:500 }}{% endblock %}
{% block page_keywords %}{{ object.keywords_as_str }} {% endblock %}

{% block extra_head %}
    <link rel="image_src"
          href="http://pythondigest.ru{% static 'img/logo.png' %}"/>

    <meta name="twitter:site" content="@pydigest"/>
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ object.title }}"/>
    <meta name="twitter:url"
          content="http://pythondigest.ru{{ object.internal_link }}"/>
    <meta name="twitter:description"
          content='{{ object.description|default:''|striptags|truncatechars:140 }}'>

    <meta property="og:type" content="article"/>
    <meta property="og:url"
          content="http://pythondigest.ru{{ object.internal_link }}"/>
    <meta property="og:title" content="{{ object.title }}"/>
    <meta property="og:site_name" content="{% trans 'Python Digesst' %}"/>
    <meta name="og:description"
          content='{{ object.description|default:''|striptags|truncatechars:500 }}'>
    <meta property="og:image"
          content="http://pythondigest.ru{% static 'img/logo.png' %}"/>
    <meta property="og:image:secure_url"
          content="http://pythondigest.ru{% static 'img/logo.png' %}"/>
    <meta property="og:image:width" content="200"/>
    <meta property="og:image:height" content="200"/>


    <meta property="og:locale" content="
    {% if object.language == 'ru' %}
        ru_RU
    {% else %}
        en_US
    {% endif %}
    "/>

    {% if object.activated_at %}
        <meta property="article:published_time"
              content="{{ object.activated_at|date:"c" }}"/>
    {% endif %}

    {% if object.modified_at %}
        <meta property="article:modified_time"
              content="{{ object.modified_at|date:"c" }}"/>
    {% endif %}

{% endblock %}



{% block body %}
<div class="news-list">
    {% with item=object read_link=True %}
        {% include 'digest/blocks/_feed_item.html' with like_link=False %}
        {% include 'digest/blocks/_item_article.html' %}
    {% endwith %}
    <hr />
    <div id="relevant_news">
        <script id="wtHREplY_Ab8W1tb">if (window.relap) window.relap.ar('wtHREplY_Ab8W1tb');</script>
    </div>
    <div class="card card-block">
        {% include "blocks/_disqus.html" %}
    </div>
</div>
{% endblock %}


{% block scripts %}
    {{ block.super }}
    {% include 'blocks/_disqus_script.html' %}
{% endblock %}

templates/digest/pages/news_list.html
{% extends "base.html" %}
{% load pytils_dt %}
{% load common %}
{% load micawber_tags %}
{% load i18n %}

{% block body %}
<div class="news-list">
    {% for item in items %}
        {% with object=item %}
            {% include 'digest/blocks/_feed_item.html' with like_link=False %}
        {% endwith %}
    {% empty %}
        <div class="alert alert-warning pull-left">
            {% blocktrans %}<strong>Its sad but true!</strong> There is no news in this feed.{% endblocktrans %}
        </div>
    {% endfor %}

    {% include "blocks/_pagination.html" %}
</div>
{% endblock %}

{% block pre_right_panel %}
    <div class="card">
        <div class="card-header">{% trans 'Language of the news' %}</div>
        {% with lang=request.GET.lang|default:'any' %}
        <div class="card-block text-xs-center">
            <a class="btn btn-secondary btn-sm {% if lang == 'any' %}active{% endif %}"
               href="{% modify_url 'del_query_param' 'lang' %}">{% trans 'Any' %}</a>
            <a class="btn btn-secondary btn-sm {% if lang == 'ru' %}active{% endif %}"
               href="{% modify_url 'set_query_param_np' 'lang' 'ru' %}">{% trans 'Russian' %}</a>
            <a class="btn btn-secondary btn-sm {% if lang == 'en' %}active{% endif %}"
               href="{% modify_url 'set_query_param_np' 'lang' 'en' %}">{% trans 'English' %}</a>
        </div>
        {% endwith %}
    </div>
{% endblock %}